spring:
  datasource:
    url: jdbc:h2:mem:weatherfit;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: 'admin'
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
decorator:
  datasource:
    p6spy:
      enable-logging: true