version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: weatherfit-mysql
    ports:
      - "3306:3306" # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: weatherfit
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --sql_mode=STRICT_TRANS_TABLES,STRICT_ALL_TABLES
#    volumes:
#      - lib/mysql/data
    networks:
      - weatherfit-network

  redis:
    image: redis:7.2.1
    container_name: weatherfit-redis
    ports:
      - "6371:6379"
    networks:
      - weatherfit-network

  batch:
    image: kjc3590/weatherfit-batch:1.0
    container_name: weatherfit-batch
    ports:
      - "8014:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - weatherfit-network

networks:
  weatherfit-network: