POST http://localhost:8080/user
Content-Type: application/json

{
  "nickName": "멋쟁이",
  "ageRange": "AGE30_39",
  "gender": "MALE",
  "height": 174
}

###

GET http://localhost:8080/style

###
POST http://localhost:8080/user/style
Content-Type: application/json

{
  "userId": 1,
  "styleIdList": [1,2,5,7]
}
