spring:
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/weatherfit?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6371
weather:
  data:
    service-key: fVxTbyzr4UCYHaz52xRECp7FjowgGOS1%2B6JgsbFcwHODs8He8MkPqZ0SqovvcKTz%2FdY0D2BMLT0XixfKLY2K%2FQ%3D%3D
  kma:
    service-key: qkoAyovRQwmKAMqL0bMJXA