spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/weatherfit?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6371